### ISSUE TITLE
Failed when using with _:

### ISSUE THREAD

**Issue by computereasy** [grantjenks/python-pattern-matching#1]
Hello, I am not sure if this project is still actively maintained. If so, I would really appreciate if someone can help me on the following issue.

I got an error for the following sample code:

```
import pypatt

@pypatt.transform
def factorial(num):
    with match(num):
        with 1:
            return 1
        with _:
            return num * factorial(num - 1)

print factorial(3)
```

Error:

```
Traceback (most recent call last):
  File "tt.py", line 29, in <module>
    print factorial(3)
  File "tt.py", line 769, in factorial

  File "/usr/lib/python2.7/site-packages/pypatt/macro.py", line 174, in trybind
    result = visitor(expr, value)
  File "/usr/lib/python2.7/site-packages/pypatt/macro.py", line 158, in visitor
    raise RuntimeError('unknown ast.Name')
RuntimeError: unknown ast.Name
```

Can anyone help me on this? Thank you

**Comment by grantjenks** [comment]
Sorry about that. It's a bug. I meant to match underscore with any object.

I may not be able to fix this for the next 6-8 weeks. Sorry. You're welcome to submit a pull request and I'll review it in a day or two.

**Comment by grantjenks** [comment]
I've abandoned the pypatt.transform decorator. Won't fix.
